import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="scroll-smooth">
            <head>
                <title>Al-Qadar</title>
                <meta
                    name="description"
                    content="This is the official website for Al-Qadar."
                />
                {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
            </head>
            <body className={`${inter.className} antialiased bg-body text-body font-body bg-orange-600 overflow-x-hidden`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
